package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "keyboard",
    srcs = ["keyboard.cc"],
    hdrs = ["keyboard.h"],
    deps = [
        "//exploratron/core",
        "//exploratron/core/utils:logging",
        "//exploratron/core/utils:terminal",
    ],
    alwayslink = 1,
)
