package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ant",
    srcs = ["ant.cc"],
    hdrs = ["ant.h"],
    deps = [
        "//exploratron/arena/common_game",
        "//exploratron/core",
        "//exploratron/core/utils:logging",
        "//exploratron/core/utils:terminal",
        "@com_google_absl//absl/strings",
    ],
    alwayslink = 1,
)
