package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "all_controllers",
    deps = [
        "//exploratron/controller/genetic",
		"//exploratron/controller/external_optimizer",
        "//exploratron/controller/hill_climbing",
        "//exploratron/controller/keyboard",
        "//exploratron/controller/random",
    ],
)
