package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "random",
    srcs = ["random.cc"],
    hdrs = ["random.h"],
    deps = [
        "//exploratron/core",
        "//exploratron/core/utils:logging",
    ],
    alwayslink = 1,
)
