package(default_visibility = ["//visibility:public"])

config_setting(
    name = "terminal_windows_console",
    values = {"define": "terminal=windows_console"},
)

config_setting(
    name = "terminal_linux_console_ncuses",
    values = {"define": "terminal=linux_console_ncuses"},
)

config_setting(
    name = "terminal_linux_console",
    values = {"define": "terminal=linux_console"},
)

config_setting(
    name = "terminal_wasm_console",
    values = {"define": "terminal=wasm_console"},
)