package(default_visibility = ["//visibility:public"])

config_setting(
    name = "terminal_windows_console",
    values = {"define": "terminal=windows_console"},
)

config_setting(
    name = "terminal_ncuses_console",
    values = {"define": "terminal=ncuses_console"},
)

config_setting(
    name = "terminal_linux_console",
    values = {"define": "terminal=linux_console"},
)

config_setting(
    name = "terminal_wasm_console",
    values = {"define": "terminal=wasm_console"},
)

config_setting(
    name = "terminal_sdl_console",
    values = {"define": "terminal=sdl_console"},
)

config_setting(
    name = "terminal_sdl_wasm_console",
    values = {"define": "terminal=sdl_wasm_console"},
)