package(default_visibility = ["//visibility:public"])

cc_library(
    name = "gather",
    srcs = ["gather.cc"],
    hdrs = ["gather.h"],
    deps = [
        "//exploratron/core",
        "//exploratron/core/utils:logging",
        "//exploratron/core/utils:terminal",
        "@com_google_absl//absl/strings",
    ],
    alwayslink = 1,
)
