package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "buffer",
    srcs = ["buffer.cc"],
    hdrs = ["buffer.h"],
    deps = [
        "//exploratron/core",
        "//exploratron/core/utils:logging",
    ],
    alwayslink = 1,
)
